/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeviceConnectivityType = { 'usb' : null } |
  { 'wifi' : null } |
  { 'ethernet' : null } |
  { 'mobileData' : null };
export interface NetworkCheckResult {
  'checkId' : bigint,
  'dnsResolutionMs' : [] | [bigint],
  'pingTimeMs' : [] | [bigint],
  'testType' : TestType,
  'description' : string,
  'errorMessages' : [] | [string],
  'timestamp' : bigint,
  'resultCode' : ResultCode,
}
export type ResultCode = { 'bad' : null } |
  { 'good' : null } |
  { 'unknown' : null };
export type TestType = { 'pingTest' : null } |
  { 'connectivityCheck' : DeviceConnectivityType } |
  { 'throughputTest' : null } |
  { 'dnsResolution' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearNetworkHistory' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserNetworkHistory' : ActorMethod<
    [Principal, [] | [bigint]],
    Array<NetworkCheckResult>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveNetworkCheckResult' : ActorMethod<[NetworkCheckResult], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];