/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DeviceConnectivityType = IDL.Variant({
  'usb' : IDL.Null,
  'wifi' : IDL.Null,
  'ethernet' : IDL.Null,
  'mobileData' : IDL.Null,
});
export const TestType = IDL.Variant({
  'pingTest' : IDL.Null,
  'connectivityCheck' : DeviceConnectivityType,
  'throughputTest' : IDL.Null,
  'dnsResolution' : IDL.Null,
});
export const ResultCode = IDL.Variant({
  'bad' : IDL.Null,
  'good' : IDL.Null,
  'unknown' : IDL.Null,
});
export const NetworkCheckResult = IDL.Record({
  'checkId' : IDL.Nat,
  'dnsResolutionMs' : IDL.Opt(IDL.Nat),
  'pingTimeMs' : IDL.Opt(IDL.Nat),
  'testType' : TestType,
  'description' : IDL.Text,
  'errorMessages' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'resultCode' : ResultCode,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearNetworkHistory' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserNetworkHistory' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Nat)],
      [IDL.Vec(NetworkCheckResult)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveNetworkCheckResult' : IDL.Func([NetworkCheckResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DeviceConnectivityType = IDL.Variant({
    'usb' : IDL.Null,
    'wifi' : IDL.Null,
    'ethernet' : IDL.Null,
    'mobileData' : IDL.Null,
  });
  const TestType = IDL.Variant({
    'pingTest' : IDL.Null,
    'connectivityCheck' : DeviceConnectivityType,
    'throughputTest' : IDL.Null,
    'dnsResolution' : IDL.Null,
  });
  const ResultCode = IDL.Variant({
    'bad' : IDL.Null,
    'good' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const NetworkCheckResult = IDL.Record({
    'checkId' : IDL.Nat,
    'dnsResolutionMs' : IDL.Opt(IDL.Nat),
    'pingTimeMs' : IDL.Opt(IDL.Nat),
    'testType' : TestType,
    'description' : IDL.Text,
    'errorMessages' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'resultCode' : ResultCode,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearNetworkHistory' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserNetworkHistory' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Nat)],
        [IDL.Vec(NetworkCheckResult)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveNetworkCheckResult' : IDL.Func([NetworkCheckResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };