/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TestType = {
    __kind__: "pingTest";
    pingTest: null;
} | {
    __kind__: "connectivityCheck";
    connectivityCheck: DeviceConnectivityType;
} | {
    __kind__: "throughputTest";
    throughputTest: null;
} | {
    __kind__: "dnsResolution";
    dnsResolution: null;
};
export interface UserProfile {
    name: string;
}
export interface NetworkCheckResult {
    checkId: bigint;
    dnsResolutionMs?: bigint;
    pingTimeMs?: bigint;
    testType: TestType;
    description: string;
    errorMessages?: string;
    timestamp: bigint;
    resultCode: ResultCode;
}
export enum DeviceConnectivityType {
    usb = "usb",
    wifi = "wifi",
    ethernet = "ethernet",
    mobileData = "mobileData"
}
export enum ResultCode {
    bad = "bad",
    good = "good",
    unknown_ = "unknown"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearNetworkHistory(): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserNetworkHistory(user: Principal, maxResults: bigint | null): Promise<Array<NetworkCheckResult>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveNetworkCheckResult(result: NetworkCheckResult): Promise<void>;
}
import type { DeviceConnectivityType as _DeviceConnectivityType, NetworkCheckResult as _NetworkCheckResult, ResultCode as _ResultCode, TestType as _TestType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearNetworkHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearNetworkHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearNetworkHistory();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserNetworkHistory(arg0: Principal, arg1: bigint | null): Promise<Array<NetworkCheckResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNetworkHistory(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNetworkHistory(arg0, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveNetworkCheckResult(arg0: NetworkCheckResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNetworkCheckResult(to_candid_NetworkCheckResult_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNetworkCheckResult(to_candid_NetworkCheckResult_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DeviceConnectivityType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviceConnectivityType): DeviceConnectivityType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_NetworkCheckResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NetworkCheckResult): NetworkCheckResult {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ResultCode_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResultCode): ResultCode {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TestType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestType): TestType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkId: bigint;
    dnsResolutionMs: [] | [bigint];
    pingTimeMs: [] | [bigint];
    testType: _TestType;
    description: string;
    errorMessages: [] | [string];
    timestamp: bigint;
    resultCode: _ResultCode;
}): {
    checkId: bigint;
    dnsResolutionMs?: bigint;
    pingTimeMs?: bigint;
    testType: TestType;
    description: string;
    errorMessages?: string;
    timestamp: bigint;
    resultCode: ResultCode;
} {
    return {
        checkId: value.checkId,
        dnsResolutionMs: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.dnsResolutionMs)),
        pingTimeMs: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.pingTimeMs)),
        testType: from_candid_TestType_n11(_uploadFile, _downloadFile, value.testType),
        description: value.description,
        errorMessages: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.errorMessages)),
        timestamp: value.timestamp,
        resultCode: from_candid_ResultCode_n16(_uploadFile, _downloadFile, value.resultCode)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pingTest: null;
} | {
    connectivityCheck: _DeviceConnectivityType;
} | {
    throughputTest: null;
} | {
    dnsResolution: null;
}): {
    __kind__: "pingTest";
    pingTest: null;
} | {
    __kind__: "connectivityCheck";
    connectivityCheck: DeviceConnectivityType;
} | {
    __kind__: "throughputTest";
    throughputTest: null;
} | {
    __kind__: "dnsResolution";
    dnsResolution: null;
} {
    return "pingTest" in value ? {
        __kind__: "pingTest",
        pingTest: value.pingTest
    } : "connectivityCheck" in value ? {
        __kind__: "connectivityCheck",
        connectivityCheck: from_candid_DeviceConnectivityType_n13(_uploadFile, _downloadFile, value.connectivityCheck)
    } : "throughputTest" in value ? {
        __kind__: "throughputTest",
        throughputTest: value.throughputTest
    } : "dnsResolution" in value ? {
        __kind__: "dnsResolution",
        dnsResolution: value.dnsResolution
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    usb: null;
} | {
    wifi: null;
} | {
    ethernet: null;
} | {
    mobileData: null;
}): DeviceConnectivityType {
    return "usb" in value ? DeviceConnectivityType.usb : "wifi" in value ? DeviceConnectivityType.wifi : "ethernet" in value ? DeviceConnectivityType.ethernet : "mobileData" in value ? DeviceConnectivityType.mobileData : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bad: null;
} | {
    good: null;
} | {
    unknown: null;
}): ResultCode {
    return "bad" in value ? ResultCode.bad : "good" in value ? ResultCode.good : "unknown" in value ? ResultCode.unknown : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NetworkCheckResult>): Array<NetworkCheckResult> {
    return value.map((x)=>from_candid_NetworkCheckResult_n8(_uploadFile, _downloadFile, x));
}
function to_candid_DeviceConnectivityType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceConnectivityType): _DeviceConnectivityType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_NetworkCheckResult_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NetworkCheckResult): _NetworkCheckResult {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_ResultCode_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResultCode): _ResultCode {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_TestType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestType): _TestType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkId: bigint;
    dnsResolutionMs?: bigint;
    pingTimeMs?: bigint;
    testType: TestType;
    description: string;
    errorMessages?: string;
    timestamp: bigint;
    resultCode: ResultCode;
}): {
    checkId: bigint;
    dnsResolutionMs: [] | [bigint];
    pingTimeMs: [] | [bigint];
    testType: _TestType;
    description: string;
    errorMessages: [] | [string];
    timestamp: bigint;
    resultCode: _ResultCode;
} {
    return {
        checkId: value.checkId,
        dnsResolutionMs: value.dnsResolutionMs ? candid_some(value.dnsResolutionMs) : candid_none(),
        pingTimeMs: value.pingTimeMs ? candid_some(value.pingTimeMs) : candid_none(),
        testType: to_candid_TestType_n20(_uploadFile, _downloadFile, value.testType),
        description: value.description,
        errorMessages: value.errorMessages ? candid_some(value.errorMessages) : candid_none(),
        timestamp: value.timestamp,
        resultCode: to_candid_ResultCode_n24(_uploadFile, _downloadFile, value.resultCode)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pingTest";
    pingTest: null;
} | {
    __kind__: "connectivityCheck";
    connectivityCheck: DeviceConnectivityType;
} | {
    __kind__: "throughputTest";
    throughputTest: null;
} | {
    __kind__: "dnsResolution";
    dnsResolution: null;
}): {
    pingTest: null;
} | {
    connectivityCheck: _DeviceConnectivityType;
} | {
    throughputTest: null;
} | {
    dnsResolution: null;
} {
    return value.__kind__ === "pingTest" ? {
        pingTest: value.pingTest
    } : value.__kind__ === "connectivityCheck" ? {
        connectivityCheck: to_candid_DeviceConnectivityType_n22(_uploadFile, _downloadFile, value.connectivityCheck)
    } : value.__kind__ === "throughputTest" ? {
        throughputTest: value.throughputTest
    } : value.__kind__ === "dnsResolution" ? {
        dnsResolution: value.dnsResolution
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceConnectivityType): {
    usb: null;
} | {
    wifi: null;
} | {
    ethernet: null;
} | {
    mobileData: null;
} {
    return value == DeviceConnectivityType.usb ? {
        usb: null
    } : value == DeviceConnectivityType.wifi ? {
        wifi: null
    } : value == DeviceConnectivityType.ethernet ? {
        ethernet: null
    } : value == DeviceConnectivityType.mobileData ? {
        mobileData: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResultCode): {
    bad: null;
} | {
    good: null;
} | {
    unknown: null;
} {
    return value == ResultCode.bad ? {
        bad: null
    } : value == ResultCode.good ? {
        good: null
    } : value == ResultCode.unknown ? {
        unknown_: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
